## سوال 1

داده‌کاوی را تعریف کنید.

---

تحلیل و پیش بینی پیامدها با توجه به اطلاعات قبلی
فرایند کشف الگو و روابط بین حجمی از داده ها که هدف ان تبدیل داده خام به ارزشمند و کمک به تصمیم گیری است

## سوال 2

تفاوت Machine Learning و Data Mining چیست؟

---

دیتا ماینینگ:کشف الگو بین اطلاعات خام و تحلیل داده
ماشین لرنینگ:ساخت مدل با استفاده از الگوها و استفاده از تحلیل ها برای یادگیری

## سوال 3

Supervised Learning چیست؟

---

یادگیری تحت نظارت:
ستون تارگت یا هدف ما برای مدل اشکار است و فقط از ارتباط بین ویژگی و هدف استفاده میکند برای یادگیری
یعنی پاسخ هر ازمون و مدل سازی از قبل مشخمص است و نیازی به پیش بینی نیست
صرفا از ورودی ها و خروجی یادمیگیرد تا داده جدید را پیش بینی کند

## سوال 4

Unsupervised Learning چیست؟

---

یادگیری بدون نظارت:
مدل هدف یا خروجی را ندارد و صرفا از داده ها برای کشف ارتباط بینشان استفاده میکند

## سوال 5

Semi-Supervised Learning چیست؟

---

یادگیری نیمه نظارتی:
ترکیبی از نظارت شده و بدون نظارت است.
یعنی از تعداد داده هایی که خروجی دارند استفاده میکند تا الگو و روابط را حفظ کند سپس با داده های بدون خروجی تمرین میکند تا دانش خود را نسبت به داده ها قوی تر کند

## سوال 6

Reinforcement Learning چیست؟

---

یادگیری تقویتی:
مدل از ازمون و خطا استفاده میکند برای یادگیری
به این صورت که عامل از محیط بابت عمل های خود عکس العمل میگیرد مثل پاداش و تنبیه
و از این عکس العمل ها به هدف میرسد
مثلا وقتی میخواهیم به یک ربات اموزش دهیم تا از یک هزارتو خارج شود.اگر از مسیر درست برود امتیاز میگیرد و برعکس
اینطوری ربات یاد میگیرد که کدام مسیرها برایس پاداش بیشتری دارد

## سوال 7

در چه شرایطی از Supervised Learning استفاده می‌کنیم؟

---

از ورودی ها و خروجی ها استفاده میکند تا بتواند داده جدید را پیش بینی کند
مثل پیش بینی قیمت یا تشخیص بیماری

## سوال 8

در چه شرایطی از Unsupervised Learning استفاده می‌کنیم؟

---

مثلا میتواند از الگوریتم استفاده کند برای دسته بندی مشتریان به گروه های مثل مشتریان وفادار یا محصولات پرطرفدار
در کل بهترین کار ان خوشه بندی اطلاعات و کمتر کردن ابعاد است

## سوال 9

Classification چیست؟

---

از خانواده ی یادگیری تحت نظارت است و گستته است
به معنی دسته بندی و به دسته ای از الگوریتم ها گفته میشود که خروجی ان یا بله یا خیر است یا انتخابی از بین چند کلاس
کاربرد:بیمار بودن با نبودن یا نوع دیابت شخص

## سوال 10

Regression چیست؟

---

از خانواده یادگیری تحت نظارت است و پیوسته است
به معنی رگرسیون و به دسته ای از الگوریتم ها گفته میشود که خروجی حتما یک عدد است
کاربرد:پیش بینی قیمت

## سوال 11

Clustering چیست؟

---

از خانواده یادگیری بدون نظارت است و گسسته
به معنی خوشه بندی و داده ها را با الگو هایی دسته بندی میکند
کاربرد:دسته بندی مشتریان

## سوال 12

Association Rule Mining چیست؟

---

از خانواده یادگیری نیمه نظارت است و گسسته است
این الگوریتم ها پیش بینی نمیکنند صرفا روابط را پیدا میکنند مثلا اگر یک مشتری کالای یک را خریده با توجه به اینکه مشتریان قبلی که کالای یک را خریده اند در کنارش کالای دو را نیز خریده اند
پس احتمال دارد این مشتری نیز به کالای دو نیاز داشته باشد
کاربرد:سبد خرید یا بازاریابی

## سوال 13

Anomaly Detection چیست؟

---

به معنی تشخیص ناهنجاری است
از بین داده ها 99درصد ان ها طبیعی اند و 1 درصد مشکوک
کاربرد:کشف تقلب بانکی یا بیمه

## سوال 14

برای هر مورد زیر نوع مسئله را مشخص کنید:

* پیش‌بینی قیمت خانه
* تشخیص سرطان
* تقسیم مشتریان
* کشف تقلب بانکی
* پیشنهاد محصول

---

پیش‌بینی قیمت خانه: از خانواده رگرسیون است چون خروجی ان عددی است
تشخیص سرطان: از خانواده دسته بندی است زیرا خروجی ان انتخابی از بین دو یا چند کلاس است
تقسیم مشتریان: از خانواده خوشه بندی است زیرا از داده ها استفاده میکند برای گروه بندی
کشف تقلب بانکی: از خانواده تشخیص ناهنجاری است زیرا این بین عمده ی تراکنش ها ان میزان کمی که مشکوک است را پیدا میکند
پیشنهاد محصول: از خانواده چهارم است و از پیدا کردن روابط استفاده میکند

## سوال 15

یک جدول تهیه کنید:

| Problem Type | Example | Algorithms |

---

In [7]:
import pandas as pd

data = {

    'Problem Type': ['Classification',
                     'Regression',
                     'Clustering',
                     'Association Rule',
                     'Anomaly Detection'],
    'Example': ['ایا شخص بیماری قلبی دارد یا خیر؟',
                'پیش بینی قیمت خانه در منطقه یک تهران',
                'محصول پر فروش در این سایت کدام است؟',
                'چه کالاهایی با هم خریداری میشوند؟',
                'تقلب صورت گرفته در تراکنشات بانکی کدام است؟'],
    'Algorithms': ['XGBoost:زیرا برای تشخیص بیماری دقت مهم ترین است',
                   'Random Forest Regressor:روابط پیچیده را بهتر درک میکند و دقت  بالایی دارد',
                   'K-Means:ساده و سریع تر است',
                   'FP-Growth:روی داده های بزرگ کند نمیشود و حافظه کمتری اشغال میکند',
                   'Isolation Forest:داده های غیر عادی را سریع جدا میکند و حافظه کمتری اشغال میکند'
                   ]
}
df = pd.DataFrame(data)
df

,Problem Type,Example,Algorithms
0,Classification,ایا شخص بیماری قلبی دارد یا خیر؟,XGBoost:زیرا برای تشخیص بیماری دقت مهم ترین است
1,Regression,پیش بینی قیمت خانه در منطقه یک تهران,Random Forest Regressor:روابط پیچیده را بهتر د...
2,Clustering,محصول پر فروش در این سایت کدام است؟,K-Means:ساده و سریع تر است
3,Association Rule,چه کالاهایی با هم خریداری میشوند؟,FP-Growth:روی داده های بزرگ کند نمیشود و حافظه...
4,Anomaly Detection,تقلب صورت گرفته در تراکنشات بانکی کدام است؟,Isolation Forest:داده های غیر عادی را سریع جدا...

## سوال 16

مسئله Heart Disease از چه نوعی است؟

---

از خانواده اول است و دسته بندی زیرا خروجی ان بله یا خیر است

## سوال 17

چرا این مسئله Classification است؟

---

ستون هدف ما تارگت است و خروجی ان بله یا خیر است

## سوال 18

چرا Regression نیست؟

---

خروجی رگرسیون عددی است و پیوسته ولی خروجی این دینتاست بله یا خیر است و گسسته

## سوال 19

چرا Clustering نیست؟

---

خوشه بندی برای دیتاست هایی است که خروجی ان ها مشخص نیست و الگوریتم باید از داده های دریافتی خودش خوشه بندی کند

## سوال 20

چرا Supervised Learning است؟

---

یادگیری با نظارت برای دیتاست هایی است که خروجی ان ها مشخص است و از تاثیر ویژگی ها روی تارگت میتوان ورودی جدید را پیش بینی کرد

## سوال 21

متغیر هدف چیست؟

---

در این دیتاست متغایر هدف ما ستون تارگت است و مدل باید الگوی رسیدن به ان را یادبگیرد تا بتواند برای ورودی های جدید از ان استفاده کند

## سوال 22

چند کلاس وجود دارد؟

---

دو کلاس
کلاس یک به معنی دارا بودن بیماری
کلاس صفر به معنی نداشتن بیماری

## سوال 23

این مسئله Binary Classification است یا Multi-Class؟

---

خروجی بله یا خیر است که به صورت باینری ذخیره شده

## سوال 24

اگر target حذف شود مسئله به چه نوعی تبدیل می‌شود؟

---

تارگت خروجی ماست که با حضور ان میتوانیم از الگوریتم های یادگیری با نظارت استفاده کنیم
حالا اگر خروجی ما حذف شود جزو الگوریتم های یادگیری بدون نظارت میشود

## سوال 25

چه معیارهایی برای موفقیت مدل اهمیت دارند؟

---

دیتا ست ما یک دیتاست پیچیده است
یعنی ترکیب چند ویژگی با هم روی تارگت تاثیر میگذارند
پس میتوان گفت تا اینجا هر ستونی حفظ شده برای موفقیت مدل ارزشمنداست

## سوال 26

پنج الگوریتم مناسب برای Binary Classification را معرفی کنید.

---

Logistic Regression:
احتمال تعلق یک نمونه به کلاس یک را حساب میکند مثلا احتمال برابر با 0.95باشد یعنی بیمار است ولی 0.32یعنی بیمار نیست
KNN:
معروف به تنبل ترین الگوریتم که با نگاه کردن به همسایه های خود تصمیم میگیرد و هرکلاسی که بیشتر تکرار شده باشد را انتخاب میکند
Desision Tree:
مثل بیست سوالی عمل میکند و سوال های متوالی میپرسد تا به نتیجه برسد
Random Forest:
مجموعه ای از درخت های تصمیم گیری است و به این گونه کار می کند که نتیجه ی 100 درخت را چک میکند
اگر 80درخت نتیجه داده باشند که بیمار است پس رای با اکثریت است
SVM:
سعی میکند بهترین مرز تصمیم گیری را بین دو کلاس در نظر بگیرد
خطی را در نظر میگیرد که دو گروه را با بیشترین فاصله از هم جدا کند
Naive Bayes:
بر اساس احتمال کار میکند و برای داده های متنی به شدت خوب کار میکند
مثلا قصد داریم تشخیص دهیم ایا این ایمیل اسپم است را خیر
میتوان با شناسایی کلماتی مثل رایگان یا جایزه ان ها را تشخیص داد

## سوال 27

مزایا و معایب Logistic Regression را بررسی کنید.

---

ایده اصلی ان این است که احتمال تعلق یک نمونه به کلاسی را حساب میکند
برای مسائل ساده تر و قابل تفسیر تر استفاده میشود و سریع است
چون برای روابط سادهن تر طراحی شده پس از پس مسائل پیچیده بر نمی اید

## سوال 28

مزایا و معایب Decision Tree را بررسی کنید.

---

درخت تصمیم گیری مثل انسان عمل میکند و با سوال پرسیدن پیش میرود
فهم ان برای انسان راحت تر است و قابل رسم است
ممکن است overfittingداشته باشد

## سوال 29

مزایا و معایب Random Forest را بررسی کنید.

---

چون از نرکیب چند درخت تصمیم گیری به نتیجه میرسد پس دقت بالایی دارد و در برابر نویز مقاوم است
ولی باز چون از نتیجه ی چند درخت تصمیم گیری است پس تفسیر سخت تری دارد

## سوال 30

مزایا و معایب SVM را بررسی کنید.

---

در این الگوریتم سعی بر این است که بهترین خط را میان دو کلاس قرار دهیم
دقت بالایی دارد و برای داده هایی که ابعاد بزرگ تری دارند نیز مناسب است
ولی اموزش ان برای داده های بزرگ تر سخت تر و زمان بر تر است . تنظیم پارامتر های ان خیلی مهم است

## سوال 31

مزایا و معایب KNN را بررسی کنید.

---

در این الگوریتم به همسایه های ان نمونه نگاه میکنیم
ساده ترین الگوریتم این گروه است و مراحل اموزش پیچیده ندارد ولی برای داده های بزرگ تر خیلی کند عمل میکند و به انتخاب مقدار همسایه ها حساس است

## سوال 32

کدام الگوریتم‌ها Explainable هستند؟

---

به الگوریتم هایی گفته میشود که برای پاسخی که میدهند باید دلیل ارائه بدهند
به زبان ساده:چرا الگوریتم این نتیجه را نشان داد؟
الگوریتم های زیر قابل توضیح هستند:
decision tree
logistic regression

## سوال 33

در حوزه پزشکی Explainability چه اهمیتی دارد؟

---

توضیح پذیری در دیتاستی که داریم روی ان کار میکنیم اهمیت بالایی دارد زیرا با سلامت جسمانی شخص در ارتباط است و مدل باید بتواند خروجی را توضیح دهد تا برای کاربر راحت تر باشد که باید چه ازمایشاتی بدهد

## سوال 34

اگر Accuracy و Explainability با هم تضاد داشته باشند کدام مهم‌تر است؟

---

دقت یعنی اینکه مدل ما چند درصد کار خود را درست انجام داده است
توضیح پذیری یعنی مدل بابت کاری که انجام داده توضیحی داشته باشد و علت تصمیم خود را بیان کند
برای اینکه کدام بهتر است در مرحله اول بستگی به خواسته ی کسب و کار دارد
ولی حالت کلی اگر میزان دقت مدل از یک درصدی پایین تر باشد یعنی الگوریتمی که برای مدل انتخاب کردیم خوب نیست و در مرحله مدل سازی باید تجدید نظر کنیم
ولی اگر در نظر بگیریم میزان دقت قابل قبول است باید از دید کسب و کار بررسی کنیم
مثلا اگر برای سناریو تفسیرپذیری مهم است پس باید از الگوریتمی استفادهن کنیم که تفسیر پذیری بالانری دارد(ممکن است بین دو الگوریتم با میزان دقت های نزدیک به هم الگوریتیمی را انتخاب کنیم که تفسیرپذیری بالا تری دارد)

## سوال 35

یک جدول تصمیم‌گیری ایجاد کنید:

| Algorithm | Pros | Cons | Suitable |

---

In [9]:
import pandas as pd

Decision_data = {
    'Algorithm': ['Logistic Regression',
                  'KNN',
                  'Desision Tree',
                  'Random Forest',
                  'SVM',
                  'Naive Bayes'],

    'Pros': ['سریع - ساده - قابل تفسیر',
             'ساده  - بدون اموزش پیچیده',
             'فهم اسان - قابل رسم',
             'دقت بالا - مقاوم در برابر نویز',
             'دقت بالا - مناسب ابعاد بالا',
             'بسیار سریع - مناسب داده متنی - عملکرد بالا با داده های کم'],

    'Cons': ['نامناسب برای داده های پیچیده',
             'کند روی داده های بزرگ - حساس به میزان همسایه های انتخابی',
             'احتمال overfitting',
             'تفسیر دشوار تر نسبت به قبلی',
             'زمان بر بودن اموزش روی داده های بزرگ تر - مهم بودن تنظیم پارامترها',
             'ویژگی ها را مستقل از هم حساب میکند'],

    'Suitable': ['مسائل ساده - قابلیت توضیح پذیری مهم است',
                 'داده ها کوچک هستند',
                 'مدل قابل فهم میخواهیم',
                 'دقت بالاتری میخواهیم - داده های بزرگ',
                 'دقت بالا مهم است - داده های زیادی داریم',
                 'داده متنی داریم - سرعت مهم است']
}
df = pd.DataFrame(Decision_data)
df

,Algorithm,Pros,Cons,Suitable
0,Logistic Regression,سریع - ساده - قابل تفسیر,نامناسب برای داده های پیچیده,مسائل ساده - قابلیت توضیح پذیری مهم است
1,KNN,ساده - بدون اموزش پیچیده,کند روی داده های بزرگ - حساس به میزان همسایه ه...,داده ها کوچک هستند
2,Desision Tree,فهم اسان - قابل رسم,احتمال overfitting,مدل قابل فهم میخواهیم
3,Random Forest,دقت بالا - مقاوم در برابر نویز,تفسیر دشوار تر نسبت به قبلی,دقت بالاتری میخواهیم - داده های بزرگ
4,SVM,دقت بالا - مناسب ابعاد بالا,زمان بر بودن اموزش روی داده های بزرگ تر - مهم ...,دقت بالا مهم است - داده های زیادی داریم
5,Naive Bayes,بسیار سریع - مناسب داده متنی - عملکرد بالا با ...,ویژگی ها را مستقل از هم حساب میکند,داده متنی داریم - سرعت مهم است

## سوال 36

سه الگوریتم نهایی خود را انتخاب کنید.

---

Decision Tree
Random Forest
SVM

## سوال 37

دلایل انتخاب هر الگوریتم را توضیح دهید.

---

Decision Tree:فهم اسانی دارد و قابل توضیح است
Random Forest:دقت بالایی دارد و نویز پذیر نیست
SVM:برای داده های زیاد مناسب است

## سوال 38

پیش‌بینی کنید کدام مدل بهترین عملکرد را خواهد داشت.

---

میزان عملکرد مدل بستگی دارد:
کیفیت داده:داده هایی که نویز ندارند یا ناقص نیستند بهترین عملکرد را دارند
حجم داده:اگر داده اموزشی بیشتر باشد مدل بهتر و با جزییات تر یاد میگیرد
الگوریتم مناسب:هر الگوریتم مناسب نوع خاصی از سناریو ها هستند
ویژگی داده:اگر ویژگی های مهم انتخاب شوند عملکرد بالاتر میرود
اور فیتیننگ و اندرفیتینگ(overfitting and underfitting)
معیارهای ارزیابی:معیارهایی مثل نگهداری اسان و سرعت و دقت و غیره سنجیده میشود و روی عملکرد تاثیر دارند

چون در این دیتاست زمان و تفسیرپذیری و دقت اهمیت بالایی دارند شاید مدلی که بر مبنای الگوریتم های svmو decision treeاست عملکرد بهتری داشته باشد

## سوال 39

پیش‌بینی کنید کدام مدل بیشترین Explainability را دارد.

---

مدلی که بر مبنای الگوریتم decision tree است توضیح پذیری بالاتری دارد

## سوال 40

پیش‌بینی کنید کدام مدل بیشترین Overfitting را خواهد داشت.

---

مدلی که الگوریتم decision treeرا دارد احتمال بیش پردازش را دارد زیرا در داده های زیاد درخت عمیق تر میشود و احتمال بیش پردازش بالا میرود

## سوال 41

چرا داده را به Train و Test تقسیم می‌کنیم؟

---

که مطمئن شویم مدل الگو ها را یادگرفته نه که حفظ کرده باشد
در trainاز داده ها استفاده میکنیم برای اموزش مدل
در testمدل را ارزیابی میکنیم که اگر داده جدید به ان بدهیم درست کار میکند یا نه

## سوال 42

خطر استفاده از کل داده برای آموزش چیست؟

---

ممکن است مدل صرفا جواب ها را حفظ کرده باشد و وقتی داده جدید به ان بدهیم عملکرد خوبی نداشته باشد

## سوال 43

مفهوم Generalization چیست؟

---

معنی لغوی ان تعمیم است و به معنی توانایی مدل برای ارائه پیش بینی درست است
یعنی اگر مدل بعد از اموزش بتواند عملکرد خوبی داشته باشد یعنی تعمیم خوبی دارد

## سوال 44

مفهوم Overfitting چیست؟

---

زمانی که مدل بیش از اندازه به داده های اموزشی وابسته شود
در این حالت احتمال دارد حتی نویزهارا حساب کند و یادبگیرد

## سوال 45

مفهوم Underfitting چیست؟

---

نقاطه مقابل overfitting است به این معنی که داده های اموزش کم بوده و مدل خوب اموزش ندیده و عملکرد ان پایین است